services:
  - name: findyourfind-web
    type: web
    env: static
    buildCommand: "" # No build command needed for PHP
    startCommand: "php -S 0.0.0.0:10000 -t ." # Starts the PHP server
    envVars:
      - key: DB_HOST
        value: monorail.proxy.rlwy.net
      - key: DB_NAME
        value: railway
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: eoqtjxUQQEaIfUysEfQSdyiBKLtLacJx
      - key: DB_PORT
        value: "51581"
